In [1]:
import torch as t

In [2]:
a = t.Tensor(2,3)

In [3]:
a

tensor([[2.2382e+10, 3.0862e-41, 2.8884e+12],
        [7.5338e+28, 2.7518e+12, 7.5338e+28]])

In [6]:
b = t.Tensor([[[1,2,3],[4,5,6]]])

In [7]:
b

tensor([[[1., 2., 3.],
         [4., 5., 6.]]])

In [8]:
b.tolist()

[[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]]

In [9]:
b_size = b.size()

In [10]:
b_size

torch.Size([1, 2, 3])

In [11]:
c = t.Tensor(b_size)

In [12]:
c

tensor([[[4.4842e-44, 1.6395e-43, 1.5414e-43],
         [1.3593e-43, 1.6535e-43, 1.3593e-43]]])

In [13]:
import torch as t
from torch import nn
from torch.autograd import Variable as V


In [15]:
class Linear(nn.Module):
    def __init__(self,in_features,out_features):
        super(Linear,self).__init__()
        self.W = nn.Parameter(t.randn(in_features,out_features))
        self.b = nn.Parameter(t.randn(out_features))
    def forward(self,x):
        x = x.m