In [2]:
import pandas as pd
import numpy as np
from tqdm import tqdm

In [2]:
pd.options.display.max_rows = 10

NameError: name 'pd' is not defined

In [ ]:
unames =['user_id','gender','age','occupation','zip']
users = pd.read_table('datasets/movielens/users.dat', sep='::',
                      header=None, names=unames)


In [86]:
x = int(1e6)

In [90]:
res = []
for i in tqdm(range(x)):
    res.append(i)
    res.append(i)
    res.append(i)
    res.append(i)
    res.append(i)
    res.append(i)

100%|██████████| 1000000/1000000 [00:01<00:00, 679005.96it/s]


In [14]:
SIZE = 1000000
arr = np.ones((SIZE,2), dtype=np.uint32)
df = pd.DataFrame(arr)

In [3]:
import datetime

In [95]:
import datetime
starttime = datetime.datetime.now()
#long running
#do something other
arr[range(SIZE),1]+=1
endtime = datetime.datetime.now()
print((endtime - starttime))


0:00:07.880109


In [97]:
import datetime
starttime = datetime.datetime.now()
#long running
#do something other
df.iloc[range(SIZE),1]+=1
endtime = datetime.datetime.now()
print((endtime - starttime))

0:00:17.330584


In [35]:
import datetime
starttime = datetime.datetime.now()
#long running
#do something other
for i in tqdm(range(1000000)):
    b =[]
    b.append(1)
    b.append(2)
    
endtime = datetime.datetime.now()
print((endtime - starttime))


100%|██████████| 1000000/1000000 [00:00<00:00, 1003378.32it/s]

0:00:01.000558


In [15]:
import datetime
starttime = datetime.datetime.now()
#long running
#do something other
for i in tqdm(range(100)):
    df.iloc[i,1]+=1
endtime = datetime.datetime.now()
print((endtime - starttime))


100%|██████████| 100/100 [00:07<00:00, 12.49it/s]

0:00:07.518873


In [62]:
data = pd.read_csv('sample.txt')
len(data)

200

In [63]:
#We label the samples with rating of 4
#and 5 to be positive and the rest to be negative
for i in range(len(data)):
    if(data.iloc[i]['rating']>=4):
        data.loc[i,'rating'] = 1
    else:
        data.loc[i,'rating'] = 0

In [75]:
#按id,时间先后排序
data = data.sort_values(by=['user_id','timestamp'],ascending = [True,True])

In [81]:
user_num = max(data['user_id'])
margin = int(user_num*0.7)

In [82]:
user_num,margin

(6040, 4228)

In [8]:
train_uid

In [9]:
max_len

2

In [10]:
from torch.nn.utils.rnn import pad_sequence

In [11]:
  uid = data['user_id'].unique()

In [31]:
        user_index_list =[]
        uid = []
        ugender = []
        uoccupation = []
        uzip = []
        uage = []
        hist_iid = []
        this_user = []
        behavior_len = []
        end = False
        for i in range(len(data)):
            if data.iloc[i]['user_id'] not in uid:
                this_user.append(data.iloc[i]['movie_id'])
                end = True
                #print(data.iloc[i]['user_id'])
                user_index_list.append(i)
                uid.append(data.iloc[i]['user_id'])
                uoccupation.append(data.iloc[i]['occupation'])
                uzip.append(data.iloc[i]['zip'])
                uage.append(data.iloc[i]['age'])
                ugender.append(data.iloc[i]['gender'])

            else: 
                this_user.append(data.iloc[i]['movie_id'])
                end = False

            if(end): 
                
                hist_iid.append(this_user)
                behavior_len.append(len(this_user))
                this_user = []


    

In [41]:
len(uid)

142

In [70]:
4 not in b

False

In [16]:
a = np.ones((10,5))

In [17]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
a = np.array([[1,2,3],
              [1,3,4],
              [1,5,6],
              [2,3,4],
              [4,5,6],
              [6,7,8]])

In [26]:
a[

array([3, 3, 4, 5, 6, 3, 4, 4, 5, 6, 6, 7, 8])

In [30]:
a[1:2,]

array([[1, 3, 4]])

In [ ]:
for i in tqdm(range(1000)):
    i = 1

In [ ]:
class TheModelClass(nn.Module):
    def __init__(self):
        super(TheModelClass, self).__init__()
        self.conv1 = nn.Conv2d()

Error: Jupyter cannot be started. Error attempting to locate jupyter: Data Science libraries jupyter and notebook are not installed in interpreter Python 2.7.12 64-bit.

In [1]:
import pandas as pd

In [11]:
d = {'col1': [1, 2], 'rating': [0, 1]}
data = pd.DataFrame(d)

In [12]:
data = data.loc[data['rating']==1]

In [13]:
data

col1  rating
1     2       1

In [2]:
!proxychains4 pip install pymysql



[proxychains] config file found: /home/zhangshengyu/config/proxychains.conf
[proxychains] preloading /home/zhangshengyu/software/proxychains4/lib/libproxychains4.so
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple


In [3]:
import pymysql

ModuleNotFoundError: No module named 'pymysql'